# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/aws-sdk-dynamodb/all/aws-sdk-dynamodb.rbi
#
# aws-sdk-dynamodb-1.44.0

module Aws::DynamoDB
end
module Aws::DynamoDB::Types
end
class Anonymous_Struct_35 < Struct
  def archival_backup_arn; end
  def archival_backup_arn=(_); end
  def archival_date_time; end
  def archival_date_time=(_); end
  def archival_reason; end
  def archival_reason=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ArchivalSummary < Anonymous_Struct_35
  include Aws::Structure
end
class Anonymous_Struct_36 < Struct
  def attribute_name; end
  def attribute_name=(_); end
  def attribute_type; end
  def attribute_type=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::AttributeDefinition < Anonymous_Struct_36
  include Aws::Structure
end
class Anonymous_Struct_37 < Struct
  def b; end
  def b=(_); end
  def bool; end
  def bool=(_); end
  def bs; end
  def bs=(_); end
  def l; end
  def l=(_); end
  def m; end
  def m=(_); end
  def n; end
  def n=(_); end
  def ns; end
  def ns=(_); end
  def null; end
  def null=(_); end
  def s; end
  def s=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def ss; end
  def ss=(_); end
end
class Aws::DynamoDB::Types::AttributeValue < Anonymous_Struct_37
  include Aws::Structure
end
class Anonymous_Struct_38 < Struct
  def action; end
  def action=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def value; end
  def value=(_); end
end
class Aws::DynamoDB::Types::AttributeValueUpdate < Anonymous_Struct_38
  include Aws::Structure
end
class Anonymous_Struct_39 < Struct
  def policy_name; end
  def policy_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def target_tracking_scaling_policy_configuration; end
  def target_tracking_scaling_policy_configuration=(_); end
end
class Aws::DynamoDB::Types::AutoScalingPolicyDescription < Anonymous_Struct_39
  include Aws::Structure
end
class Anonymous_Struct_40 < Struct
  def policy_name; end
  def policy_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def target_tracking_scaling_policy_configuration; end
  def target_tracking_scaling_policy_configuration=(_); end
end
class Aws::DynamoDB::Types::AutoScalingPolicyUpdate < Anonymous_Struct_40
  include Aws::Structure
end
class Anonymous_Struct_41 < Struct
  def auto_scaling_disabled; end
  def auto_scaling_disabled=(_); end
  def auto_scaling_role_arn; end
  def auto_scaling_role_arn=(_); end
  def maximum_units; end
  def maximum_units=(_); end
  def minimum_units; end
  def minimum_units=(_); end
  def scaling_policies; end
  def scaling_policies=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::AutoScalingSettingsDescription < Anonymous_Struct_41
  include Aws::Structure
end
class Anonymous_Struct_42 < Struct
  def auto_scaling_disabled; end
  def auto_scaling_disabled=(_); end
  def auto_scaling_role_arn; end
  def auto_scaling_role_arn=(_); end
  def maximum_units; end
  def maximum_units=(_); end
  def minimum_units; end
  def minimum_units=(_); end
  def scaling_policy_update; end
  def scaling_policy_update=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::AutoScalingSettingsUpdate < Anonymous_Struct_42
  include Aws::Structure
end
class Anonymous_Struct_43 < Struct
  def disable_scale_in; end
  def disable_scale_in=(_); end
  def scale_in_cooldown; end
  def scale_in_cooldown=(_); end
  def scale_out_cooldown; end
  def scale_out_cooldown=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def target_value; end
  def target_value=(_); end
end
class Aws::DynamoDB::Types::AutoScalingTargetTrackingScalingPolicyConfigurationDescription < Anonymous_Struct_43
  include Aws::Structure
end
class Anonymous_Struct_44 < Struct
  def disable_scale_in; end
  def disable_scale_in=(_); end
  def scale_in_cooldown; end
  def scale_in_cooldown=(_); end
  def scale_out_cooldown; end
  def scale_out_cooldown=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def target_value; end
  def target_value=(_); end
end
class Aws::DynamoDB::Types::AutoScalingTargetTrackingScalingPolicyConfigurationUpdate < Anonymous_Struct_44
  include Aws::Structure
end
class Anonymous_Struct_45 < Struct
  def backup_details; end
  def backup_details=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def source_table_details; end
  def source_table_details=(_); end
  def source_table_feature_details; end
  def source_table_feature_details=(_); end
end
class Aws::DynamoDB::Types::BackupDescription < Anonymous_Struct_45
  include Aws::Structure
end
class Anonymous_Struct_46 < Struct
  def backup_arn; end
  def backup_arn=(_); end
  def backup_creation_date_time; end
  def backup_creation_date_time=(_); end
  def backup_expiry_date_time; end
  def backup_expiry_date_time=(_); end
  def backup_name; end
  def backup_name=(_); end
  def backup_size_bytes; end
  def backup_size_bytes=(_); end
  def backup_status; end
  def backup_status=(_); end
  def backup_type; end
  def backup_type=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::BackupDetails < Anonymous_Struct_46
  include Aws::Structure
end
class Anonymous_Struct_47 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::BackupInUseException < Anonymous_Struct_47
  include Aws::Structure
end
class Anonymous_Struct_48 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::BackupNotFoundException < Anonymous_Struct_48
  include Aws::Structure
end
class Anonymous_Struct_49 < Struct
  def backup_arn; end
  def backup_arn=(_); end
  def backup_creation_date_time; end
  def backup_creation_date_time=(_); end
  def backup_expiry_date_time; end
  def backup_expiry_date_time=(_); end
  def backup_name; end
  def backup_name=(_); end
  def backup_size_bytes; end
  def backup_size_bytes=(_); end
  def backup_status; end
  def backup_status=(_); end
  def backup_type; end
  def backup_type=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_arn; end
  def table_arn=(_); end
  def table_id; end
  def table_id=(_); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::BackupSummary < Anonymous_Struct_49
  include Aws::Structure
end
class Anonymous_Struct_50 < Struct
  def request_items; end
  def request_items=(_); end
  def return_consumed_capacity; end
  def return_consumed_capacity=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::BatchGetItemInput < Anonymous_Struct_50
  include Aws::Structure
end
class Anonymous_Struct_51 < Struct
  def consumed_capacity; end
  def consumed_capacity=(_); end
  def responses; end
  def responses=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def unprocessed_keys; end
  def unprocessed_keys=(_); end
end
class Aws::DynamoDB::Types::BatchGetItemOutput < Anonymous_Struct_51
  include Aws::Structure
end
class Anonymous_Struct_52 < Struct
  def request_items; end
  def request_items=(_); end
  def return_consumed_capacity; end
  def return_consumed_capacity=(_); end
  def return_item_collection_metrics; end
  def return_item_collection_metrics=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::BatchWriteItemInput < Anonymous_Struct_52
  include Aws::Structure
end
class Anonymous_Struct_53 < Struct
  def consumed_capacity; end
  def consumed_capacity=(_); end
  def item_collection_metrics; end
  def item_collection_metrics=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def unprocessed_items; end
  def unprocessed_items=(_); end
end
class Aws::DynamoDB::Types::BatchWriteItemOutput < Anonymous_Struct_53
  include Aws::Structure
end
class Anonymous_Struct_54 < Struct
  def billing_mode; end
  def billing_mode=(_); end
  def last_update_to_pay_per_request_date_time; end
  def last_update_to_pay_per_request_date_time=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::BillingModeSummary < Anonymous_Struct_54
  include Aws::Structure
end
class Anonymous_Struct_55 < Struct
  def code; end
  def code=(_); end
  def item; end
  def item=(_); end
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::CancellationReason < Anonymous_Struct_55
  include Aws::Structure
end
class Anonymous_Struct_56 < Struct
  def capacity_units; end
  def capacity_units=(_); end
  def read_capacity_units; end
  def read_capacity_units=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def write_capacity_units; end
  def write_capacity_units=(_); end
end
class Aws::DynamoDB::Types::Capacity < Anonymous_Struct_56
  include Aws::Structure
end
class Anonymous_Struct_57 < Struct
  def attribute_value_list; end
  def attribute_value_list=(_); end
  def comparison_operator; end
  def comparison_operator=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::Condition < Anonymous_Struct_57
  include Aws::Structure
end
class Anonymous_Struct_58 < Struct
  def condition_expression; end
  def condition_expression=(_); end
  def expression_attribute_names; end
  def expression_attribute_names=(_); end
  def expression_attribute_values; end
  def expression_attribute_values=(_); end
  def key; end
  def key=(_); end
  def return_values_on_condition_check_failure; end
  def return_values_on_condition_check_failure=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::ConditionCheck < Anonymous_Struct_58
  include Aws::Structure
end
class Anonymous_Struct_59 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ConditionalCheckFailedException < Anonymous_Struct_59
  include Aws::Structure
end
class Anonymous_Struct_60 < Struct
  def capacity_units; end
  def capacity_units=(_); end
  def global_secondary_indexes; end
  def global_secondary_indexes=(_); end
  def local_secondary_indexes; end
  def local_secondary_indexes=(_); end
  def read_capacity_units; end
  def read_capacity_units=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table; end
  def table=(_); end
  def table_name; end
  def table_name=(_); end
  def write_capacity_units; end
  def write_capacity_units=(_); end
end
class Aws::DynamoDB::Types::ConsumedCapacity < Anonymous_Struct_60
  include Aws::Structure
end
class Anonymous_Struct_61 < Struct
  def continuous_backups_status; end
  def continuous_backups_status=(_); end
  def point_in_time_recovery_description; end
  def point_in_time_recovery_description=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ContinuousBackupsDescription < Anonymous_Struct_61
  include Aws::Structure
end
class Anonymous_Struct_62 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ContinuousBackupsUnavailableException < Anonymous_Struct_62
  include Aws::Structure
end
class Anonymous_Struct_63 < Struct
  def contributor_insights_status; end
  def contributor_insights_status=(_); end
  def index_name; end
  def index_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::ContributorInsightsSummary < Anonymous_Struct_63
  include Aws::Structure
end
class Anonymous_Struct_64 < Struct
  def backup_name; end
  def backup_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::CreateBackupInput < Anonymous_Struct_64
  include Aws::Structure
end
class Anonymous_Struct_65 < Struct
  def backup_details; end
  def backup_details=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::CreateBackupOutput < Anonymous_Struct_65
  include Aws::Structure
end
class Anonymous_Struct_66 < Struct
  def index_name; end
  def index_name=(_); end
  def key_schema; end
  def key_schema=(_); end
  def projection; end
  def projection=(_); end
  def provisioned_throughput; end
  def provisioned_throughput=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::CreateGlobalSecondaryIndexAction < Anonymous_Struct_66
  include Aws::Structure
end
class Anonymous_Struct_67 < Struct
  def global_table_name; end
  def global_table_name=(_); end
  def replication_group; end
  def replication_group=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::CreateGlobalTableInput < Anonymous_Struct_67
  include Aws::Structure
end
class Anonymous_Struct_68 < Struct
  def global_table_description; end
  def global_table_description=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::CreateGlobalTableOutput < Anonymous_Struct_68
  include Aws::Structure
end
class Anonymous_Struct_69 < Struct
  def region_name; end
  def region_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::CreateReplicaAction < Anonymous_Struct_69
  include Aws::Structure
end
class Anonymous_Struct_70 < Struct
  def global_secondary_indexes; end
  def global_secondary_indexes=(_); end
  def kms_master_key_id; end
  def kms_master_key_id=(_); end
  def provisioned_throughput_override; end
  def provisioned_throughput_override=(_); end
  def region_name; end
  def region_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::CreateReplicationGroupMemberAction < Anonymous_Struct_70
  include Aws::Structure
end
class Anonymous_Struct_71 < Struct
  def attribute_definitions; end
  def attribute_definitions=(_); end
  def billing_mode; end
  def billing_mode=(_); end
  def global_secondary_indexes; end
  def global_secondary_indexes=(_); end
  def key_schema; end
  def key_schema=(_); end
  def local_secondary_indexes; end
  def local_secondary_indexes=(_); end
  def provisioned_throughput; end
  def provisioned_throughput=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def sse_specification; end
  def sse_specification=(_); end
  def stream_specification; end
  def stream_specification=(_); end
  def table_name; end
  def table_name=(_); end
  def tags; end
  def tags=(_); end
end
class Aws::DynamoDB::Types::CreateTableInput < Anonymous_Struct_71
  include Aws::Structure
end
class Anonymous_Struct_72 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_description; end
  def table_description=(_); end
end
class Aws::DynamoDB::Types::CreateTableOutput < Anonymous_Struct_72
  include Aws::Structure
end
class Anonymous_Struct_73 < Struct
  def condition_expression; end
  def condition_expression=(_); end
  def expression_attribute_names; end
  def expression_attribute_names=(_); end
  def expression_attribute_values; end
  def expression_attribute_values=(_); end
  def key; end
  def key=(_); end
  def return_values_on_condition_check_failure; end
  def return_values_on_condition_check_failure=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::Delete < Anonymous_Struct_73
  include Aws::Structure
end
class Anonymous_Struct_74 < Struct
  def backup_arn; end
  def backup_arn=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DeleteBackupInput < Anonymous_Struct_74
  include Aws::Structure
end
class Anonymous_Struct_75 < Struct
  def backup_description; end
  def backup_description=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DeleteBackupOutput < Anonymous_Struct_75
  include Aws::Structure
end
class Anonymous_Struct_76 < Struct
  def index_name; end
  def index_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DeleteGlobalSecondaryIndexAction < Anonymous_Struct_76
  include Aws::Structure
end
class Anonymous_Struct_77 < Struct
  def condition_expression; end
  def condition_expression=(_); end
  def conditional_operator; end
  def conditional_operator=(_); end
  def expected; end
  def expected=(_); end
  def expression_attribute_names; end
  def expression_attribute_names=(_); end
  def expression_attribute_values; end
  def expression_attribute_values=(_); end
  def key; end
  def key=(_); end
  def return_consumed_capacity; end
  def return_consumed_capacity=(_); end
  def return_item_collection_metrics; end
  def return_item_collection_metrics=(_); end
  def return_values; end
  def return_values=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::DeleteItemInput < Anonymous_Struct_77
  include Aws::Structure
end
class Anonymous_Struct_78 < Struct
  def attributes; end
  def attributes=(_); end
  def consumed_capacity; end
  def consumed_capacity=(_); end
  def item_collection_metrics; end
  def item_collection_metrics=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DeleteItemOutput < Anonymous_Struct_78
  include Aws::Structure
end
class Anonymous_Struct_79 < Struct
  def region_name; end
  def region_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DeleteReplicaAction < Anonymous_Struct_79
  include Aws::Structure
end
class Anonymous_Struct_80 < Struct
  def region_name; end
  def region_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DeleteReplicationGroupMemberAction < Anonymous_Struct_80
  include Aws::Structure
end
class Anonymous_Struct_81 < Struct
  def key; end
  def key=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DeleteRequest < Anonymous_Struct_81
  include Aws::Structure
end
class Anonymous_Struct_82 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::DeleteTableInput < Anonymous_Struct_82
  include Aws::Structure
end
class Anonymous_Struct_83 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_description; end
  def table_description=(_); end
end
class Aws::DynamoDB::Types::DeleteTableOutput < Anonymous_Struct_83
  include Aws::Structure
end
class Anonymous_Struct_84 < Struct
  def backup_arn; end
  def backup_arn=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DescribeBackupInput < Anonymous_Struct_84
  include Aws::Structure
end
class Anonymous_Struct_85 < Struct
  def backup_description; end
  def backup_description=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DescribeBackupOutput < Anonymous_Struct_85
  include Aws::Structure
end
class Anonymous_Struct_86 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::DescribeContinuousBackupsInput < Anonymous_Struct_86
  include Aws::Structure
end
class Anonymous_Struct_87 < Struct
  def continuous_backups_description; end
  def continuous_backups_description=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DescribeContinuousBackupsOutput < Anonymous_Struct_87
  include Aws::Structure
end
class Anonymous_Struct_88 < Struct
  def index_name; end
  def index_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::DescribeContributorInsightsInput < Anonymous_Struct_88
  include Aws::Structure
end
class Anonymous_Struct_89 < Struct
  def contributor_insights_rule_list; end
  def contributor_insights_rule_list=(_); end
  def contributor_insights_status; end
  def contributor_insights_status=(_); end
  def failure_exception; end
  def failure_exception=(_); end
  def index_name; end
  def index_name=(_); end
  def last_update_date_time; end
  def last_update_date_time=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::DescribeContributorInsightsOutput < Anonymous_Struct_89
  include Aws::Structure
end
class Aws::DynamoDB::Types::DescribeEndpointsRequest < Aws::EmptyStructure
end
class Anonymous_Struct_90 < Struct
  def endpoints; end
  def endpoints=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DescribeEndpointsResponse < Anonymous_Struct_90
  include Aws::Structure
end
class Anonymous_Struct_91 < Struct
  def global_table_name; end
  def global_table_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DescribeGlobalTableInput < Anonymous_Struct_91
  include Aws::Structure
end
class Anonymous_Struct_92 < Struct
  def global_table_description; end
  def global_table_description=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DescribeGlobalTableOutput < Anonymous_Struct_92
  include Aws::Structure
end
class Anonymous_Struct_93 < Struct
  def global_table_name; end
  def global_table_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DescribeGlobalTableSettingsInput < Anonymous_Struct_93
  include Aws::Structure
end
class Anonymous_Struct_94 < Struct
  def global_table_name; end
  def global_table_name=(_); end
  def replica_settings; end
  def replica_settings=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::DescribeGlobalTableSettingsOutput < Anonymous_Struct_94
  include Aws::Structure
end
class Aws::DynamoDB::Types::DescribeLimitsInput < Aws::EmptyStructure
end
class Anonymous_Struct_95 < Struct
  def account_max_read_capacity_units; end
  def account_max_read_capacity_units=(_); end
  def account_max_write_capacity_units; end
  def account_max_write_capacity_units=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_max_read_capacity_units; end
  def table_max_read_capacity_units=(_); end
  def table_max_write_capacity_units; end
  def table_max_write_capacity_units=(_); end
end
class Aws::DynamoDB::Types::DescribeLimitsOutput < Anonymous_Struct_95
  include Aws::Structure
end
class Anonymous_Struct_96 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::DescribeTableInput < Anonymous_Struct_96
  include Aws::Structure
end
class Anonymous_Struct_97 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table; end
  def table=(_); end
end
class Aws::DynamoDB::Types::DescribeTableOutput < Anonymous_Struct_97
  include Aws::Structure
end
class Anonymous_Struct_98 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::DescribeTableReplicaAutoScalingInput < Anonymous_Struct_98
  include Aws::Structure
end
class Anonymous_Struct_99 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_auto_scaling_description; end
  def table_auto_scaling_description=(_); end
end
class Aws::DynamoDB::Types::DescribeTableReplicaAutoScalingOutput < Anonymous_Struct_99
  include Aws::Structure
end
class Anonymous_Struct_100 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::DescribeTimeToLiveInput < Anonymous_Struct_100
  include Aws::Structure
end
class Anonymous_Struct_101 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def time_to_live_description; end
  def time_to_live_description=(_); end
end
class Aws::DynamoDB::Types::DescribeTimeToLiveOutput < Anonymous_Struct_101
  include Aws::Structure
end
class Anonymous_Struct_102 < Struct
  def address; end
  def address=(_); end
  def cache_period_in_minutes; end
  def cache_period_in_minutes=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::Endpoint < Anonymous_Struct_102
  include Aws::Structure
end
class Anonymous_Struct_103 < Struct
  def attribute_value_list; end
  def attribute_value_list=(_); end
  def comparison_operator; end
  def comparison_operator=(_); end
  def exists; end
  def exists=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def value; end
  def value=(_); end
end
class Aws::DynamoDB::Types::ExpectedAttributeValue < Anonymous_Struct_103
  include Aws::Structure
end
class Anonymous_Struct_104 < Struct
  def exception_description; end
  def exception_description=(_); end
  def exception_name; end
  def exception_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::FailureException < Anonymous_Struct_104
  include Aws::Structure
end
class Anonymous_Struct_105 < Struct
  def expression_attribute_names; end
  def expression_attribute_names=(_); end
  def key; end
  def key=(_); end
  def projection_expression; end
  def projection_expression=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::Get < Anonymous_Struct_105
  include Aws::Structure
end
class Anonymous_Struct_106 < Struct
  def attributes_to_get; end
  def attributes_to_get=(_); end
  def consistent_read; end
  def consistent_read=(_); end
  def expression_attribute_names; end
  def expression_attribute_names=(_); end
  def key; end
  def key=(_); end
  def projection_expression; end
  def projection_expression=(_); end
  def return_consumed_capacity; end
  def return_consumed_capacity=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::GetItemInput < Anonymous_Struct_106
  include Aws::Structure
end
class Anonymous_Struct_107 < Struct
  def consumed_capacity; end
  def consumed_capacity=(_); end
  def item; end
  def item=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::GetItemOutput < Anonymous_Struct_107
  include Aws::Structure
end
class Anonymous_Struct_108 < Struct
  def index_name; end
  def index_name=(_); end
  def key_schema; end
  def key_schema=(_); end
  def projection; end
  def projection=(_); end
  def provisioned_throughput; end
  def provisioned_throughput=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::GlobalSecondaryIndex < Anonymous_Struct_108
  include Aws::Structure
end
class Anonymous_Struct_109 < Struct
  def index_name; end
  def index_name=(_); end
  def provisioned_write_capacity_auto_scaling_update; end
  def provisioned_write_capacity_auto_scaling_update=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::GlobalSecondaryIndexAutoScalingUpdate < Anonymous_Struct_109
  include Aws::Structure
end
class Anonymous_Struct_110 < Struct
  def backfilling; end
  def backfilling=(_); end
  def index_arn; end
  def index_arn=(_); end
  def index_name; end
  def index_name=(_); end
  def index_size_bytes; end
  def index_size_bytes=(_); end
  def index_status; end
  def index_status=(_); end
  def item_count; end
  def item_count=(_); end
  def key_schema; end
  def key_schema=(_); end
  def projection; end
  def projection=(_); end
  def provisioned_throughput; end
  def provisioned_throughput=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::GlobalSecondaryIndexDescription < Anonymous_Struct_110
  include Aws::Structure
end
class Anonymous_Struct_111 < Struct
  def index_name; end
  def index_name=(_); end
  def key_schema; end
  def key_schema=(_); end
  def projection; end
  def projection=(_); end
  def provisioned_throughput; end
  def provisioned_throughput=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::GlobalSecondaryIndexInfo < Anonymous_Struct_111
  include Aws::Structure
end
class Anonymous_Struct_112 < Struct
  def create; end
  def create=(_); end
  def delete; end
  def delete=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def update; end
  def update=(_); end
end
class Aws::DynamoDB::Types::GlobalSecondaryIndexUpdate < Anonymous_Struct_112
  include Aws::Structure
end
class Anonymous_Struct_113 < Struct
  def global_table_name; end
  def global_table_name=(_); end
  def replication_group; end
  def replication_group=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::GlobalTable < Anonymous_Struct_113
  include Aws::Structure
end
class Anonymous_Struct_114 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::GlobalTableAlreadyExistsException < Anonymous_Struct_114
  include Aws::Structure
end
class Anonymous_Struct_115 < Struct
  def creation_date_time; end
  def creation_date_time=(_); end
  def global_table_arn; end
  def global_table_arn=(_); end
  def global_table_name; end
  def global_table_name=(_); end
  def global_table_status; end
  def global_table_status=(_); end
  def replication_group; end
  def replication_group=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::GlobalTableDescription < Anonymous_Struct_115
  include Aws::Structure
end
class Anonymous_Struct_116 < Struct
  def index_name; end
  def index_name=(_); end
  def provisioned_write_capacity_auto_scaling_settings_update; end
  def provisioned_write_capacity_auto_scaling_settings_update=(_); end
  def provisioned_write_capacity_units; end
  def provisioned_write_capacity_units=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::GlobalTableGlobalSecondaryIndexSettingsUpdate < Anonymous_Struct_116
  include Aws::Structure
end
class Anonymous_Struct_117 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::GlobalTableNotFoundException < Anonymous_Struct_117
  include Aws::Structure
end
class Anonymous_Struct_118 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::IdempotentParameterMismatchException < Anonymous_Struct_118
  include Aws::Structure
end
class Anonymous_Struct_119 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::IndexNotFoundException < Anonymous_Struct_119
  include Aws::Structure
end
class Anonymous_Struct_120 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::InternalServerError < Anonymous_Struct_120
  include Aws::Structure
end
class Anonymous_Struct_121 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::InvalidRestoreTimeException < Anonymous_Struct_121
  include Aws::Structure
end
class Anonymous_Struct_122 < Struct
  def item_collection_key; end
  def item_collection_key=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def size_estimate_range_gb; end
  def size_estimate_range_gb=(_); end
end
class Aws::DynamoDB::Types::ItemCollectionMetrics < Anonymous_Struct_122
  include Aws::Structure
end
class Anonymous_Struct_123 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ItemCollectionSizeLimitExceededException < Anonymous_Struct_123
  include Aws::Structure
end
class Anonymous_Struct_124 < Struct
  def item; end
  def item=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ItemResponse < Anonymous_Struct_124
  include Aws::Structure
end
class Anonymous_Struct_125 < Struct
  def attribute_name; end
  def attribute_name=(_); end
  def key_type; end
  def key_type=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::KeySchemaElement < Anonymous_Struct_125
  include Aws::Structure
end
class Anonymous_Struct_126 < Struct
  def attributes_to_get; end
  def attributes_to_get=(_); end
  def consistent_read; end
  def consistent_read=(_); end
  def expression_attribute_names; end
  def expression_attribute_names=(_); end
  def keys; end
  def keys=(_); end
  def projection_expression; end
  def projection_expression=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::KeysAndAttributes < Anonymous_Struct_126
  include Aws::Structure
end
class Anonymous_Struct_127 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::LimitExceededException < Anonymous_Struct_127
  include Aws::Structure
end
class Anonymous_Struct_128 < Struct
  def backup_type; end
  def backup_type=(_); end
  def exclusive_start_backup_arn; end
  def exclusive_start_backup_arn=(_); end
  def limit; end
  def limit=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
  def time_range_lower_bound; end
  def time_range_lower_bound=(_); end
  def time_range_upper_bound; end
  def time_range_upper_bound=(_); end
end
class Aws::DynamoDB::Types::ListBackupsInput < Anonymous_Struct_128
  include Aws::Structure
end
class Anonymous_Struct_129 < Struct
  def backup_summaries; end
  def backup_summaries=(_); end
  def last_evaluated_backup_arn; end
  def last_evaluated_backup_arn=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ListBackupsOutput < Anonymous_Struct_129
  include Aws::Structure
end
class Anonymous_Struct_130 < Struct
  def max_results; end
  def max_results=(_); end
  def next_token; end
  def next_token=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::ListContributorInsightsInput < Anonymous_Struct_130
  include Aws::Structure
end
class Anonymous_Struct_131 < Struct
  def contributor_insights_summaries; end
  def contributor_insights_summaries=(_); end
  def next_token; end
  def next_token=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ListContributorInsightsOutput < Anonymous_Struct_131
  include Aws::Structure
end
class Anonymous_Struct_132 < Struct
  def exclusive_start_global_table_name; end
  def exclusive_start_global_table_name=(_); end
  def limit; end
  def limit=(_); end
  def region_name; end
  def region_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ListGlobalTablesInput < Anonymous_Struct_132
  include Aws::Structure
end
class Anonymous_Struct_133 < Struct
  def global_tables; end
  def global_tables=(_); end
  def last_evaluated_global_table_name; end
  def last_evaluated_global_table_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ListGlobalTablesOutput < Anonymous_Struct_133
  include Aws::Structure
end
class Anonymous_Struct_134 < Struct
  def exclusive_start_table_name; end
  def exclusive_start_table_name=(_); end
  def limit; end
  def limit=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ListTablesInput < Anonymous_Struct_134
  include Aws::Structure
end
class Anonymous_Struct_135 < Struct
  def last_evaluated_table_name; end
  def last_evaluated_table_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_names; end
  def table_names=(_); end
end
class Aws::DynamoDB::Types::ListTablesOutput < Anonymous_Struct_135
  include Aws::Structure
end
class Anonymous_Struct_136 < Struct
  def next_token; end
  def next_token=(_); end
  def resource_arn; end
  def resource_arn=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ListTagsOfResourceInput < Anonymous_Struct_136
  include Aws::Structure
end
class Anonymous_Struct_137 < Struct
  def next_token; end
  def next_token=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def tags; end
  def tags=(_); end
end
class Aws::DynamoDB::Types::ListTagsOfResourceOutput < Anonymous_Struct_137
  include Aws::Structure
end
class Anonymous_Struct_138 < Struct
  def index_name; end
  def index_name=(_); end
  def key_schema; end
  def key_schema=(_); end
  def projection; end
  def projection=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::LocalSecondaryIndex < Anonymous_Struct_138
  include Aws::Structure
end
class Anonymous_Struct_139 < Struct
  def index_arn; end
  def index_arn=(_); end
  def index_name; end
  def index_name=(_); end
  def index_size_bytes; end
  def index_size_bytes=(_); end
  def item_count; end
  def item_count=(_); end
  def key_schema; end
  def key_schema=(_); end
  def projection; end
  def projection=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::LocalSecondaryIndexDescription < Anonymous_Struct_139
  include Aws::Structure
end
class Anonymous_Struct_140 < Struct
  def index_name; end
  def index_name=(_); end
  def key_schema; end
  def key_schema=(_); end
  def projection; end
  def projection=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::LocalSecondaryIndexInfo < Anonymous_Struct_140
  include Aws::Structure
end
class Anonymous_Struct_141 < Struct
  def earliest_restorable_date_time; end
  def earliest_restorable_date_time=(_); end
  def latest_restorable_date_time; end
  def latest_restorable_date_time=(_); end
  def point_in_time_recovery_status; end
  def point_in_time_recovery_status=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::PointInTimeRecoveryDescription < Anonymous_Struct_141
  include Aws::Structure
end
class Anonymous_Struct_142 < Struct
  def point_in_time_recovery_enabled; end
  def point_in_time_recovery_enabled=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::PointInTimeRecoverySpecification < Anonymous_Struct_142
  include Aws::Structure
end
class Anonymous_Struct_143 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::PointInTimeRecoveryUnavailableException < Anonymous_Struct_143
  include Aws::Structure
end
class Anonymous_Struct_144 < Struct
  def non_key_attributes; end
  def non_key_attributes=(_); end
  def projection_type; end
  def projection_type=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::Projection < Anonymous_Struct_144
  include Aws::Structure
end
class Anonymous_Struct_145 < Struct
  def read_capacity_units; end
  def read_capacity_units=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def write_capacity_units; end
  def write_capacity_units=(_); end
end
class Aws::DynamoDB::Types::ProvisionedThroughput < Anonymous_Struct_145
  include Aws::Structure
end
class Anonymous_Struct_146 < Struct
  def last_decrease_date_time; end
  def last_decrease_date_time=(_); end
  def last_increase_date_time; end
  def last_increase_date_time=(_); end
  def number_of_decreases_today; end
  def number_of_decreases_today=(_); end
  def read_capacity_units; end
  def read_capacity_units=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def write_capacity_units; end
  def write_capacity_units=(_); end
end
class Aws::DynamoDB::Types::ProvisionedThroughputDescription < Anonymous_Struct_146
  include Aws::Structure
end
class Anonymous_Struct_147 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ProvisionedThroughputExceededException < Anonymous_Struct_147
  include Aws::Structure
end
class Anonymous_Struct_148 < Struct
  def read_capacity_units; end
  def read_capacity_units=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ProvisionedThroughputOverride < Anonymous_Struct_148
  include Aws::Structure
end
class Anonymous_Struct_149 < Struct
  def condition_expression; end
  def condition_expression=(_); end
  def expression_attribute_names; end
  def expression_attribute_names=(_); end
  def expression_attribute_values; end
  def expression_attribute_values=(_); end
  def item; end
  def item=(_); end
  def return_values_on_condition_check_failure; end
  def return_values_on_condition_check_failure=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::Put < Anonymous_Struct_149
  include Aws::Structure
end
class Anonymous_Struct_150 < Struct
  def condition_expression; end
  def condition_expression=(_); end
  def conditional_operator; end
  def conditional_operator=(_); end
  def expected; end
  def expected=(_); end
  def expression_attribute_names; end
  def expression_attribute_names=(_); end
  def expression_attribute_values; end
  def expression_attribute_values=(_); end
  def item; end
  def item=(_); end
  def return_consumed_capacity; end
  def return_consumed_capacity=(_); end
  def return_item_collection_metrics; end
  def return_item_collection_metrics=(_); end
  def return_values; end
  def return_values=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::PutItemInput < Anonymous_Struct_150
  include Aws::Structure
end
class Anonymous_Struct_151 < Struct
  def attributes; end
  def attributes=(_); end
  def consumed_capacity; end
  def consumed_capacity=(_); end
  def item_collection_metrics; end
  def item_collection_metrics=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::PutItemOutput < Anonymous_Struct_151
  include Aws::Structure
end
class Anonymous_Struct_152 < Struct
  def item; end
  def item=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::PutRequest < Anonymous_Struct_152
  include Aws::Structure
end
class Anonymous_Struct_153 < Struct
  def attributes_to_get; end
  def attributes_to_get=(_); end
  def conditional_operator; end
  def conditional_operator=(_); end
  def consistent_read; end
  def consistent_read=(_); end
  def exclusive_start_key; end
  def exclusive_start_key=(_); end
  def expression_attribute_names; end
  def expression_attribute_names=(_); end
  def expression_attribute_values; end
  def expression_attribute_values=(_); end
  def filter_expression; end
  def filter_expression=(_); end
  def index_name; end
  def index_name=(_); end
  def key_condition_expression; end
  def key_condition_expression=(_); end
  def key_conditions; end
  def key_conditions=(_); end
  def limit; end
  def limit=(_); end
  def projection_expression; end
  def projection_expression=(_); end
  def query_filter; end
  def query_filter=(_); end
  def return_consumed_capacity; end
  def return_consumed_capacity=(_); end
  def scan_index_forward; end
  def scan_index_forward=(_); end
  def select; end
  def select=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::QueryInput < Anonymous_Struct_153
  include Aws::Structure
end
class Anonymous_Struct_154 < Struct
  def consumed_capacity; end
  def consumed_capacity=(_); end
  def count; end
  def count=(_); end
  def items; end
  def items=(_); end
  def last_evaluated_key; end
  def last_evaluated_key=(_); end
  def scanned_count; end
  def scanned_count=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::QueryOutput < Anonymous_Struct_154
  include Aws::Structure
end
class Anonymous_Struct_155 < Struct
  def region_name; end
  def region_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::Replica < Anonymous_Struct_155
  include Aws::Structure
end
class Anonymous_Struct_156 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ReplicaAlreadyExistsException < Anonymous_Struct_156
  include Aws::Structure
end
class Anonymous_Struct_157 < Struct
  def global_secondary_indexes; end
  def global_secondary_indexes=(_); end
  def region_name; end
  def region_name=(_); end
  def replica_provisioned_read_capacity_auto_scaling_settings; end
  def replica_provisioned_read_capacity_auto_scaling_settings=(_); end
  def replica_provisioned_write_capacity_auto_scaling_settings; end
  def replica_provisioned_write_capacity_auto_scaling_settings=(_); end
  def replica_status; end
  def replica_status=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ReplicaAutoScalingDescription < Anonymous_Struct_157
  include Aws::Structure
end
class Anonymous_Struct_158 < Struct
  def region_name; end
  def region_name=(_); end
  def replica_global_secondary_index_updates; end
  def replica_global_secondary_index_updates=(_); end
  def replica_provisioned_read_capacity_auto_scaling_update; end
  def replica_provisioned_read_capacity_auto_scaling_update=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ReplicaAutoScalingUpdate < Anonymous_Struct_158
  include Aws::Structure
end
class Anonymous_Struct_159 < Struct
  def global_secondary_indexes; end
  def global_secondary_indexes=(_); end
  def kms_master_key_id; end
  def kms_master_key_id=(_); end
  def provisioned_throughput_override; end
  def provisioned_throughput_override=(_); end
  def region_name; end
  def region_name=(_); end
  def replica_status; end
  def replica_status=(_); end
  def replica_status_description; end
  def replica_status_description=(_); end
  def replica_status_percent_progress; end
  def replica_status_percent_progress=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ReplicaDescription < Anonymous_Struct_159
  include Aws::Structure
end
class Anonymous_Struct_160 < Struct
  def index_name; end
  def index_name=(_); end
  def provisioned_throughput_override; end
  def provisioned_throughput_override=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ReplicaGlobalSecondaryIndex < Anonymous_Struct_160
  include Aws::Structure
end
class Anonymous_Struct_161 < Struct
  def index_name; end
  def index_name=(_); end
  def index_status; end
  def index_status=(_); end
  def provisioned_read_capacity_auto_scaling_settings; end
  def provisioned_read_capacity_auto_scaling_settings=(_); end
  def provisioned_write_capacity_auto_scaling_settings; end
  def provisioned_write_capacity_auto_scaling_settings=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ReplicaGlobalSecondaryIndexAutoScalingDescription < Anonymous_Struct_161
  include Aws::Structure
end
class Anonymous_Struct_162 < Struct
  def index_name; end
  def index_name=(_); end
  def provisioned_read_capacity_auto_scaling_update; end
  def provisioned_read_capacity_auto_scaling_update=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ReplicaGlobalSecondaryIndexAutoScalingUpdate < Anonymous_Struct_162
  include Aws::Structure
end
class Anonymous_Struct_163 < Struct
  def index_name; end
  def index_name=(_); end
  def provisioned_throughput_override; end
  def provisioned_throughput_override=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ReplicaGlobalSecondaryIndexDescription < Anonymous_Struct_163
  include Aws::Structure
end
class Anonymous_Struct_164 < Struct
  def index_name; end
  def index_name=(_); end
  def index_status; end
  def index_status=(_); end
  def provisioned_read_capacity_auto_scaling_settings; end
  def provisioned_read_capacity_auto_scaling_settings=(_); end
  def provisioned_read_capacity_units; end
  def provisioned_read_capacity_units=(_); end
  def provisioned_write_capacity_auto_scaling_settings; end
  def provisioned_write_capacity_auto_scaling_settings=(_); end
  def provisioned_write_capacity_units; end
  def provisioned_write_capacity_units=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ReplicaGlobalSecondaryIndexSettingsDescription < Anonymous_Struct_164
  include Aws::Structure
end
class Anonymous_Struct_165 < Struct
  def index_name; end
  def index_name=(_); end
  def provisioned_read_capacity_auto_scaling_settings_update; end
  def provisioned_read_capacity_auto_scaling_settings_update=(_); end
  def provisioned_read_capacity_units; end
  def provisioned_read_capacity_units=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ReplicaGlobalSecondaryIndexSettingsUpdate < Anonymous_Struct_165
  include Aws::Structure
end
class Anonymous_Struct_166 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ReplicaNotFoundException < Anonymous_Struct_166
  include Aws::Structure
end
class Anonymous_Struct_167 < Struct
  def region_name; end
  def region_name=(_); end
  def replica_billing_mode_summary; end
  def replica_billing_mode_summary=(_); end
  def replica_global_secondary_index_settings; end
  def replica_global_secondary_index_settings=(_); end
  def replica_provisioned_read_capacity_auto_scaling_settings; end
  def replica_provisioned_read_capacity_auto_scaling_settings=(_); end
  def replica_provisioned_read_capacity_units; end
  def replica_provisioned_read_capacity_units=(_); end
  def replica_provisioned_write_capacity_auto_scaling_settings; end
  def replica_provisioned_write_capacity_auto_scaling_settings=(_); end
  def replica_provisioned_write_capacity_units; end
  def replica_provisioned_write_capacity_units=(_); end
  def replica_status; end
  def replica_status=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ReplicaSettingsDescription < Anonymous_Struct_167
  include Aws::Structure
end
class Anonymous_Struct_168 < Struct
  def region_name; end
  def region_name=(_); end
  def replica_global_secondary_index_settings_update; end
  def replica_global_secondary_index_settings_update=(_); end
  def replica_provisioned_read_capacity_auto_scaling_settings_update; end
  def replica_provisioned_read_capacity_auto_scaling_settings_update=(_); end
  def replica_provisioned_read_capacity_units; end
  def replica_provisioned_read_capacity_units=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ReplicaSettingsUpdate < Anonymous_Struct_168
  include Aws::Structure
end
class Anonymous_Struct_169 < Struct
  def create; end
  def create=(_); end
  def delete; end
  def delete=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ReplicaUpdate < Anonymous_Struct_169
  include Aws::Structure
end
class Anonymous_Struct_170 < Struct
  def create; end
  def create=(_); end
  def delete; end
  def delete=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def update; end
  def update=(_); end
end
class Aws::DynamoDB::Types::ReplicationGroupUpdate < Anonymous_Struct_170
  include Aws::Structure
end
class Anonymous_Struct_171 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::RequestLimitExceeded < Anonymous_Struct_171
  include Aws::Structure
end
class Anonymous_Struct_172 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ResourceInUseException < Anonymous_Struct_172
  include Aws::Structure
end
class Anonymous_Struct_173 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ResourceNotFoundException < Anonymous_Struct_173
  include Aws::Structure
end
class Anonymous_Struct_174 < Struct
  def restore_date_time; end
  def restore_date_time=(_); end
  def restore_in_progress; end
  def restore_in_progress=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def source_backup_arn; end
  def source_backup_arn=(_); end
  def source_table_arn; end
  def source_table_arn=(_); end
end
class Aws::DynamoDB::Types::RestoreSummary < Anonymous_Struct_174
  include Aws::Structure
end
class Anonymous_Struct_175 < Struct
  def backup_arn; end
  def backup_arn=(_); end
  def billing_mode_override; end
  def billing_mode_override=(_); end
  def global_secondary_index_override; end
  def global_secondary_index_override=(_); end
  def local_secondary_index_override; end
  def local_secondary_index_override=(_); end
  def provisioned_throughput_override; end
  def provisioned_throughput_override=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def sse_specification_override; end
  def sse_specification_override=(_); end
  def target_table_name; end
  def target_table_name=(_); end
end
class Aws::DynamoDB::Types::RestoreTableFromBackupInput < Anonymous_Struct_175
  include Aws::Structure
end
class Anonymous_Struct_176 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_description; end
  def table_description=(_); end
end
class Aws::DynamoDB::Types::RestoreTableFromBackupOutput < Anonymous_Struct_176
  include Aws::Structure
end
class Anonymous_Struct_177 < Struct
  def billing_mode_override; end
  def billing_mode_override=(_); end
  def global_secondary_index_override; end
  def global_secondary_index_override=(_); end
  def local_secondary_index_override; end
  def local_secondary_index_override=(_); end
  def provisioned_throughput_override; end
  def provisioned_throughput_override=(_); end
  def restore_date_time; end
  def restore_date_time=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def source_table_arn; end
  def source_table_arn=(_); end
  def source_table_name; end
  def source_table_name=(_); end
  def sse_specification_override; end
  def sse_specification_override=(_); end
  def target_table_name; end
  def target_table_name=(_); end
  def use_latest_restorable_time; end
  def use_latest_restorable_time=(_); end
end
class Aws::DynamoDB::Types::RestoreTableToPointInTimeInput < Anonymous_Struct_177
  include Aws::Structure
end
class Anonymous_Struct_178 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_description; end
  def table_description=(_); end
end
class Aws::DynamoDB::Types::RestoreTableToPointInTimeOutput < Anonymous_Struct_178
  include Aws::Structure
end
class Anonymous_Struct_179 < Struct
  def inaccessible_encryption_date_time; end
  def inaccessible_encryption_date_time=(_); end
  def kms_master_key_arn; end
  def kms_master_key_arn=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def sse_type; end
  def sse_type=(_); end
  def status; end
  def status=(_); end
end
class Aws::DynamoDB::Types::SSEDescription < Anonymous_Struct_179
  include Aws::Structure
end
class Anonymous_Struct_180 < Struct
  def enabled; end
  def enabled=(_); end
  def kms_master_key_id; end
  def kms_master_key_id=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def sse_type; end
  def sse_type=(_); end
end
class Aws::DynamoDB::Types::SSESpecification < Anonymous_Struct_180
  include Aws::Structure
end
class Anonymous_Struct_181 < Struct
  def attributes_to_get; end
  def attributes_to_get=(_); end
  def conditional_operator; end
  def conditional_operator=(_); end
  def consistent_read; end
  def consistent_read=(_); end
  def exclusive_start_key; end
  def exclusive_start_key=(_); end
  def expression_attribute_names; end
  def expression_attribute_names=(_); end
  def expression_attribute_values; end
  def expression_attribute_values=(_); end
  def filter_expression; end
  def filter_expression=(_); end
  def index_name; end
  def index_name=(_); end
  def limit; end
  def limit=(_); end
  def projection_expression; end
  def projection_expression=(_); end
  def return_consumed_capacity; end
  def return_consumed_capacity=(_); end
  def scan_filter; end
  def scan_filter=(_); end
  def segment; end
  def segment=(_); end
  def select; end
  def select=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
  def total_segments; end
  def total_segments=(_); end
end
class Aws::DynamoDB::Types::ScanInput < Anonymous_Struct_181
  include Aws::Structure
end
class Anonymous_Struct_182 < Struct
  def consumed_capacity; end
  def consumed_capacity=(_); end
  def count; end
  def count=(_); end
  def items; end
  def items=(_); end
  def last_evaluated_key; end
  def last_evaluated_key=(_); end
  def scanned_count; end
  def scanned_count=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::ScanOutput < Anonymous_Struct_182
  include Aws::Structure
end
class Anonymous_Struct_183 < Struct
  def billing_mode; end
  def billing_mode=(_); end
  def item_count; end
  def item_count=(_); end
  def key_schema; end
  def key_schema=(_); end
  def provisioned_throughput; end
  def provisioned_throughput=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_arn; end
  def table_arn=(_); end
  def table_creation_date_time; end
  def table_creation_date_time=(_); end
  def table_id; end
  def table_id=(_); end
  def table_name; end
  def table_name=(_); end
  def table_size_bytes; end
  def table_size_bytes=(_); end
end
class Aws::DynamoDB::Types::SourceTableDetails < Anonymous_Struct_183
  include Aws::Structure
end
class Anonymous_Struct_184 < Struct
  def global_secondary_indexes; end
  def global_secondary_indexes=(_); end
  def local_secondary_indexes; end
  def local_secondary_indexes=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def sse_description; end
  def sse_description=(_); end
  def stream_description; end
  def stream_description=(_); end
  def time_to_live_description; end
  def time_to_live_description=(_); end
end
class Aws::DynamoDB::Types::SourceTableFeatureDetails < Anonymous_Struct_184
  include Aws::Structure
end
class Anonymous_Struct_185 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def stream_enabled; end
  def stream_enabled=(_); end
  def stream_view_type; end
  def stream_view_type=(_); end
end
class Aws::DynamoDB::Types::StreamSpecification < Anonymous_Struct_185
  include Aws::Structure
end
class Anonymous_Struct_186 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::TableAlreadyExistsException < Anonymous_Struct_186
  include Aws::Structure
end
class Anonymous_Struct_187 < Struct
  def replicas; end
  def replicas=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
  def table_status; end
  def table_status=(_); end
end
class Aws::DynamoDB::Types::TableAutoScalingDescription < Anonymous_Struct_187
  include Aws::Structure
end
class Anonymous_Struct_188 < Struct
  def archival_summary; end
  def archival_summary=(_); end
  def attribute_definitions; end
  def attribute_definitions=(_); end
  def billing_mode_summary; end
  def billing_mode_summary=(_); end
  def creation_date_time; end
  def creation_date_time=(_); end
  def global_secondary_indexes; end
  def global_secondary_indexes=(_); end
  def global_table_version; end
  def global_table_version=(_); end
  def item_count; end
  def item_count=(_); end
  def key_schema; end
  def key_schema=(_); end
  def latest_stream_arn; end
  def latest_stream_arn=(_); end
  def latest_stream_label; end
  def latest_stream_label=(_); end
  def local_secondary_indexes; end
  def local_secondary_indexes=(_); end
  def provisioned_throughput; end
  def provisioned_throughput=(_); end
  def replicas; end
  def replicas=(_); end
  def restore_summary; end
  def restore_summary=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def sse_description; end
  def sse_description=(_); end
  def stream_specification; end
  def stream_specification=(_); end
  def table_arn; end
  def table_arn=(_); end
  def table_id; end
  def table_id=(_); end
  def table_name; end
  def table_name=(_); end
  def table_size_bytes; end
  def table_size_bytes=(_); end
  def table_status; end
  def table_status=(_); end
end
class Aws::DynamoDB::Types::TableDescription < Anonymous_Struct_188
  include Aws::Structure
end
class Anonymous_Struct_189 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::TableInUseException < Anonymous_Struct_189
  include Aws::Structure
end
class Anonymous_Struct_190 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::TableNotFoundException < Anonymous_Struct_190
  include Aws::Structure
end
class Anonymous_Struct_191 < Struct
  def key; end
  def key=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def value; end
  def value=(_); end
end
class Aws::DynamoDB::Types::Tag < Anonymous_Struct_191
  include Aws::Structure
end
class Anonymous_Struct_192 < Struct
  def resource_arn; end
  def resource_arn=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def tags; end
  def tags=(_); end
end
class Aws::DynamoDB::Types::TagResourceInput < Anonymous_Struct_192
  include Aws::Structure
end
class Anonymous_Struct_193 < Struct
  def attribute_name; end
  def attribute_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def time_to_live_status; end
  def time_to_live_status=(_); end
end
class Aws::DynamoDB::Types::TimeToLiveDescription < Anonymous_Struct_193
  include Aws::Structure
end
class Anonymous_Struct_194 < Struct
  def attribute_name; end
  def attribute_name=(_); end
  def enabled; end
  def enabled=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::TimeToLiveSpecification < Anonymous_Struct_194
  include Aws::Structure
end
class Anonymous_Struct_195 < Struct
  def get; end
  def get=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::TransactGetItem < Anonymous_Struct_195
  include Aws::Structure
end
class Anonymous_Struct_196 < Struct
  def return_consumed_capacity; end
  def return_consumed_capacity=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def transact_items; end
  def transact_items=(_); end
end
class Aws::DynamoDB::Types::TransactGetItemsInput < Anonymous_Struct_196
  include Aws::Structure
end
class Anonymous_Struct_197 < Struct
  def consumed_capacity; end
  def consumed_capacity=(_); end
  def responses; end
  def responses=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::TransactGetItemsOutput < Anonymous_Struct_197
  include Aws::Structure
end
class Anonymous_Struct_198 < Struct
  def condition_check; end
  def condition_check=(_); end
  def delete; end
  def delete=(_); end
  def put; end
  def put=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def update; end
  def update=(_); end
end
class Aws::DynamoDB::Types::TransactWriteItem < Anonymous_Struct_198
  include Aws::Structure
end
class Anonymous_Struct_199 < Struct
  def client_request_token; end
  def client_request_token=(_); end
  def return_consumed_capacity; end
  def return_consumed_capacity=(_); end
  def return_item_collection_metrics; end
  def return_item_collection_metrics=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def transact_items; end
  def transact_items=(_); end
end
class Aws::DynamoDB::Types::TransactWriteItemsInput < Anonymous_Struct_199
  include Aws::Structure
end
class Anonymous_Struct_200 < Struct
  def consumed_capacity; end
  def consumed_capacity=(_); end
  def item_collection_metrics; end
  def item_collection_metrics=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::TransactWriteItemsOutput < Anonymous_Struct_200
  include Aws::Structure
end
class Anonymous_Struct_201 < Struct
  def cancellation_reasons; end
  def cancellation_reasons=(_); end
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::TransactionCanceledException < Anonymous_Struct_201
  include Aws::Structure
end
class Anonymous_Struct_202 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::TransactionConflictException < Anonymous_Struct_202
  include Aws::Structure
end
class Anonymous_Struct_203 < Struct
  def message; end
  def message=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::TransactionInProgressException < Anonymous_Struct_203
  include Aws::Structure
end
class Anonymous_Struct_204 < Struct
  def resource_arn; end
  def resource_arn=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def tag_keys; end
  def tag_keys=(_); end
end
class Aws::DynamoDB::Types::UntagResourceInput < Anonymous_Struct_204
  include Aws::Structure
end
class Anonymous_Struct_205 < Struct
  def condition_expression; end
  def condition_expression=(_); end
  def expression_attribute_names; end
  def expression_attribute_names=(_); end
  def expression_attribute_values; end
  def expression_attribute_values=(_); end
  def key; end
  def key=(_); end
  def return_values_on_condition_check_failure; end
  def return_values_on_condition_check_failure=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
  def update_expression; end
  def update_expression=(_); end
end
class Aws::DynamoDB::Types::Update < Anonymous_Struct_205
  include Aws::Structure
end
class Anonymous_Struct_206 < Struct
  def point_in_time_recovery_specification; end
  def point_in_time_recovery_specification=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::UpdateContinuousBackupsInput < Anonymous_Struct_206
  include Aws::Structure
end
class Anonymous_Struct_207 < Struct
  def continuous_backups_description; end
  def continuous_backups_description=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::UpdateContinuousBackupsOutput < Anonymous_Struct_207
  include Aws::Structure
end
class Anonymous_Struct_208 < Struct
  def contributor_insights_action; end
  def contributor_insights_action=(_); end
  def index_name; end
  def index_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::UpdateContributorInsightsInput < Anonymous_Struct_208
  include Aws::Structure
end
class Anonymous_Struct_209 < Struct
  def contributor_insights_status; end
  def contributor_insights_status=(_); end
  def index_name; end
  def index_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::UpdateContributorInsightsOutput < Anonymous_Struct_209
  include Aws::Structure
end
class Anonymous_Struct_210 < Struct
  def index_name; end
  def index_name=(_); end
  def provisioned_throughput; end
  def provisioned_throughput=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::UpdateGlobalSecondaryIndexAction < Anonymous_Struct_210
  include Aws::Structure
end
class Anonymous_Struct_211 < Struct
  def global_table_name; end
  def global_table_name=(_); end
  def replica_updates; end
  def replica_updates=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::UpdateGlobalTableInput < Anonymous_Struct_211
  include Aws::Structure
end
class Anonymous_Struct_212 < Struct
  def global_table_description; end
  def global_table_description=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::UpdateGlobalTableOutput < Anonymous_Struct_212
  include Aws::Structure
end
class Anonymous_Struct_213 < Struct
  def global_table_billing_mode; end
  def global_table_billing_mode=(_); end
  def global_table_global_secondary_index_settings_update; end
  def global_table_global_secondary_index_settings_update=(_); end
  def global_table_name; end
  def global_table_name=(_); end
  def global_table_provisioned_write_capacity_auto_scaling_settings_update; end
  def global_table_provisioned_write_capacity_auto_scaling_settings_update=(_); end
  def global_table_provisioned_write_capacity_units; end
  def global_table_provisioned_write_capacity_units=(_); end
  def replica_settings_update; end
  def replica_settings_update=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::UpdateGlobalTableSettingsInput < Anonymous_Struct_213
  include Aws::Structure
end
class Anonymous_Struct_214 < Struct
  def global_table_name; end
  def global_table_name=(_); end
  def replica_settings; end
  def replica_settings=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::UpdateGlobalTableSettingsOutput < Anonymous_Struct_214
  include Aws::Structure
end
class Anonymous_Struct_215 < Struct
  def attribute_updates; end
  def attribute_updates=(_); end
  def condition_expression; end
  def condition_expression=(_); end
  def conditional_operator; end
  def conditional_operator=(_); end
  def expected; end
  def expected=(_); end
  def expression_attribute_names; end
  def expression_attribute_names=(_); end
  def expression_attribute_values; end
  def expression_attribute_values=(_); end
  def key; end
  def key=(_); end
  def return_consumed_capacity; end
  def return_consumed_capacity=(_); end
  def return_item_collection_metrics; end
  def return_item_collection_metrics=(_); end
  def return_values; end
  def return_values=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
  def update_expression; end
  def update_expression=(_); end
end
class Aws::DynamoDB::Types::UpdateItemInput < Anonymous_Struct_215
  include Aws::Structure
end
class Anonymous_Struct_216 < Struct
  def attributes; end
  def attributes=(_); end
  def consumed_capacity; end
  def consumed_capacity=(_); end
  def item_collection_metrics; end
  def item_collection_metrics=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::UpdateItemOutput < Anonymous_Struct_216
  include Aws::Structure
end
class Anonymous_Struct_217 < Struct
  def global_secondary_indexes; end
  def global_secondary_indexes=(_); end
  def kms_master_key_id; end
  def kms_master_key_id=(_); end
  def provisioned_throughput_override; end
  def provisioned_throughput_override=(_); end
  def region_name; end
  def region_name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::UpdateReplicationGroupMemberAction < Anonymous_Struct_217
  include Aws::Structure
end
class Anonymous_Struct_218 < Struct
  def attribute_definitions; end
  def attribute_definitions=(_); end
  def billing_mode; end
  def billing_mode=(_); end
  def global_secondary_index_updates; end
  def global_secondary_index_updates=(_); end
  def provisioned_throughput; end
  def provisioned_throughput=(_); end
  def replica_updates; end
  def replica_updates=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def sse_specification; end
  def sse_specification=(_); end
  def stream_specification; end
  def stream_specification=(_); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::UpdateTableInput < Anonymous_Struct_218
  include Aws::Structure
end
class Anonymous_Struct_219 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_description; end
  def table_description=(_); end
end
class Aws::DynamoDB::Types::UpdateTableOutput < Anonymous_Struct_219
  include Aws::Structure
end
class Anonymous_Struct_220 < Struct
  def global_secondary_index_updates; end
  def global_secondary_index_updates=(_); end
  def provisioned_write_capacity_auto_scaling_update; end
  def provisioned_write_capacity_auto_scaling_update=(_); end
  def replica_updates; end
  def replica_updates=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
end
class Aws::DynamoDB::Types::UpdateTableReplicaAutoScalingInput < Anonymous_Struct_220
  include Aws::Structure
end
class Anonymous_Struct_221 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_auto_scaling_description; end
  def table_auto_scaling_description=(_); end
end
class Aws::DynamoDB::Types::UpdateTableReplicaAutoScalingOutput < Anonymous_Struct_221
  include Aws::Structure
end
class Anonymous_Struct_222 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def table_name; end
  def table_name=(_); end
  def time_to_live_specification; end
  def time_to_live_specification=(_); end
end
class Aws::DynamoDB::Types::UpdateTimeToLiveInput < Anonymous_Struct_222
  include Aws::Structure
end
class Anonymous_Struct_223 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def time_to_live_specification; end
  def time_to_live_specification=(_); end
end
class Aws::DynamoDB::Types::UpdateTimeToLiveOutput < Anonymous_Struct_223
  include Aws::Structure
end
class Anonymous_Struct_224 < Struct
  def delete_request; end
  def delete_request=(_); end
  def put_request; end
  def put_request=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Aws::DynamoDB::Types::WriteRequest < Anonymous_Struct_224
  include Aws::Structure
end
module Aws::DynamoDB::ClientApi
  include Seahorse::Model
end
module Aws
end
module Aws::DynamoDB::Plugins
end
class Aws::DynamoDB::Plugins::ExtendedRetries < Seahorse::Client::Plugin
end
class Aws::DynamoDB::Plugins::SimpleAttributes < Seahorse::Client::Plugin
  def add_handlers(handlers, config); end
end
class Aws::DynamoDB::Plugins::SimpleAttributes::Handler < Seahorse::Client::Handler
  def call(context); end
  def translate_input(context); end
  def translate_output(response); end
end
class Aws::DynamoDB::Plugins::SimpleAttributes::ValueTranslator
  def apply(values); end
  def initialize(rules, mode); end
  def list(ref, values); end
  def map(ref, values); end
  def self.apply(rules, mode, data); end
  def structure(ref, values); end
  def translate(ref, value); end
  def translate_complex(ref, value); end
  include Seahorse::Model::Shapes
end
class Aws::DynamoDB::Plugins::CRC32Validation < Seahorse::Client::Plugin
  def add_handlers(handlers, config); end
end
class Aws::DynamoDB::Plugins::CRC32Validation::Handler < Seahorse::Client::Handler
  def call(context); end
  def crc32_is_valid?(response); end
  def validate(context); end
end
class Aws::DynamoDB::Client < Seahorse::Client::Base
  def batch_get_item(params = nil, options = nil); end
  def batch_write_item(params = nil, options = nil); end
  def build_request(operation_name, params = nil); end
  def create_backup(params = nil, options = nil); end
  def create_global_table(params = nil, options = nil); end
  def create_table(params = nil, options = nil); end
  def data_to_http_resp(operation_name, data); end
  def delete_backup(params = nil, options = nil); end
  def delete_item(params = nil, options = nil); end
  def delete_table(params = nil, options = nil); end
  def describe_backup(params = nil, options = nil); end
  def describe_continuous_backups(params = nil, options = nil); end
  def describe_contributor_insights(params = nil, options = nil); end
  def describe_endpoints(params = nil, options = nil); end
  def describe_global_table(params = nil, options = nil); end
  def describe_global_table_settings(params = nil, options = nil); end
  def describe_limits(params = nil, options = nil); end
  def describe_table(params = nil, options = nil); end
  def describe_table_replica_auto_scaling(params = nil, options = nil); end
  def describe_time_to_live(params = nil, options = nil); end
  def get_item(params = nil, options = nil); end
  def initialize(*args); end
  def list_backups(params = nil, options = nil); end
  def list_contributor_insights(params = nil, options = nil); end
  def list_global_tables(params = nil, options = nil); end
  def list_tables(params = nil, options = nil); end
  def list_tags_of_resource(params = nil, options = nil); end
  def put_item(params = nil, options = nil); end
  def query(params = nil, options = nil); end
  def restore_table_from_backup(params = nil, options = nil); end
  def restore_table_to_point_in_time(params = nil, options = nil); end
  def scan(params = nil, options = nil); end
  def self.errors_module; end
  def self.identifier; end
  def stub_data(operation_name, data = nil); end
  def tag_resource(params = nil, options = nil); end
  def transact_get_items(params = nil, options = nil); end
  def transact_write_items(params = nil, options = nil); end
  def untag_resource(params = nil, options = nil); end
  def update_continuous_backups(params = nil, options = nil); end
  def update_contributor_insights(params = nil, options = nil); end
  def update_global_table(params = nil, options = nil); end
  def update_global_table_settings(params = nil, options = nil); end
  def update_item(params = nil, options = nil); end
  def update_table(params = nil, options = nil); end
  def update_table_replica_auto_scaling(params = nil, options = nil); end
  def update_time_to_live(params = nil, options = nil); end
  def wait_until(waiter_name, params = nil, options = nil); end
  def waiter(waiter_name, options = nil); end
  def waiter_names; end
  def waiters; end
  include Anonymous_Module_225
  include Aws::ClientStubs
end
module Anonymous_Module_225
  def batch_get_item(*args, &block); end
  def batch_write_item(*args, &block); end
  def create_backup(*args, &block); end
  def create_global_table(*args, &block); end
  def create_table(*args, &block); end
  def delete_backup(*args, &block); end
  def delete_item(*args, &block); end
  def delete_table(*args, &block); end
  def describe_backup(*args, &block); end
  def describe_continuous_backups(*args, &block); end
  def describe_contributor_insights(*args, &block); end
  def describe_endpoints(*args, &block); end
  def describe_global_table(*args, &block); end
  def describe_global_table_settings(*args, &block); end
  def describe_limits(*args, &block); end
  def describe_table(*args, &block); end
  def describe_table_replica_auto_scaling(*args, &block); end
  def describe_time_to_live(*args, &block); end
  def get_item(*args, &block); end
  def list_backups(*args, &block); end
  def list_contributor_insights(*args, &block); end
  def list_global_tables(*args, &block); end
  def list_tables(*args, &block); end
  def list_tags_of_resource(*args, &block); end
  def put_item(*args, &block); end
  def query(*args, &block); end
  def restore_table_from_backup(*args, &block); end
  def restore_table_to_point_in_time(*args, &block); end
  def scan(*args, &block); end
  def tag_resource(*args, &block); end
  def transact_get_items(*args, &block); end
  def transact_write_items(*args, &block); end
  def untag_resource(*args, &block); end
  def update_continuous_backups(*args, &block); end
  def update_contributor_insights(*args, &block); end
  def update_global_table(*args, &block); end
  def update_global_table_settings(*args, &block); end
  def update_item(*args, &block); end
  def update_table(*args, &block); end
  def update_table_replica_auto_scaling(*args, &block); end
  def update_time_to_live(*args, &block); end
end
module Aws::DynamoDB::Errors
  extend Aws::Errors::DynamicErrors
end
class Aws::DynamoDB::Errors::ServiceError < Aws::Errors::ServiceError
end
class Aws::DynamoDB::Errors::BackupInUseException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::BackupNotFoundException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::ConditionalCheckFailedException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::ContinuousBackupsUnavailableException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::GlobalTableAlreadyExistsException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::GlobalTableNotFoundException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::IdempotentParameterMismatchException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::IndexNotFoundException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::InternalServerError < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::InvalidRestoreTimeException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::ItemCollectionSizeLimitExceededException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::LimitExceededException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::PointInTimeRecoveryUnavailableException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::ProvisionedThroughputExceededException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::ReplicaAlreadyExistsException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::ReplicaNotFoundException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::RequestLimitExceeded < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::ResourceInUseException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::ResourceNotFoundException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::TableAlreadyExistsException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::TableInUseException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::TableNotFoundException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::TransactionCanceledException < Aws::DynamoDB::Errors::ServiceError
  def cancellation_reasons; end
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::TransactionConflictException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
class Aws::DynamoDB::Errors::TransactionInProgressException < Aws::DynamoDB::Errors::ServiceError
  def initialize(context, message, data = nil); end
  def message; end
end
module Aws::DynamoDB::Waiters
end
class Aws::DynamoDB::Waiters::TableExists
  def initialize(options); end
  def wait(params = nil); end
  def waiter; end
end
class Aws::DynamoDB::Waiters::TableNotExists
  def initialize(options); end
  def wait(params = nil); end
  def waiter; end
end
class Aws::DynamoDB::Resource
  def batch_get_item(options = nil); end
  def batch_write_item(options = nil); end
  def client; end
  def create_table(options = nil); end
  def initialize(options = nil); end
  def table(name); end
  def tables(options = nil); end
end
class Aws::DynamoDB::Table
  def archival_summary; end
  def attribute_definitions; end
  def billing_mode_summary; end
  def client; end
  def creation_date_time; end
  def data; end
  def data_loaded?; end
  def delete(options = nil); end
  def delete_item(options = nil); end
  def deprecated_identifiers; end
  def extract_name(args, options); end
  def get_item(options = nil); end
  def global_secondary_indexes; end
  def global_table_version; end
  def identifiers(*args, &block); end
  def initialize(*args); end
  def item_count; end
  def key_schema; end
  def latest_stream_arn; end
  def latest_stream_label; end
  def load; end
  def local_secondary_indexes; end
  def name; end
  def provisioned_throughput; end
  def put_item(options = nil); end
  def query(options = nil); end
  def reload; end
  def replicas; end
  def restore_summary; end
  def scan(options = nil); end
  def sse_description; end
  def stream_specification; end
  def table_arn; end
  def table_id; end
  def table_name; end
  def table_size_bytes; end
  def table_status; end
  def update(options = nil); end
  def update_item(options = nil); end
  def wait_until(options = nil, &block); end
  extend Aws::Deprecations
end
class Aws::DynamoDB::Table::Collection < Aws::Resources::Collection
end
class Aws::DynamoDB::AttributeValue
  def initialize; end
  def marshal(value); end
  def unmarshal(value); end
end
class Aws::DynamoDB::AttributeValue::Marshaler
  def format(obj); end
  def format_set(set); end
end
class Aws::DynamoDB::AttributeValue::Unmarshaler
  def extract_type_and_value(obj); end
  def format(obj); end
end
