AllCops:
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
