# frozen_string_literal: true

# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_3; end
class ::SlackRouter; end
module ActiveSupport::ActionController::Base; end
module GarageView::SlackRouter; end
